# Generated by Django 2.1.7 on 2019-04-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='courses.Course'),
        ),
    ]
