# Generated by Django 2.1.7 on 2019-05-27 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    # replaces = [('courses', '0001_initial'), ('courses', '0002_auto_20190327_1400'), ('courses', '0003_questionnaire_choices_per_question'), ('courses', '0004_auto_20190328_0904'), ('courses', '0005_remove_questionnaire_img'), ('courses', '0006_auto_20190328_0930'), ('courses', '0007_remove_question_other_posible_answers'), ('courses', '0008_auto_20190328_1254'), ('courses', '0009_auto_20190328_1254'), ('courses', '0010_auto_20190328_1639'), ('courses', '0011_questionnaire_treat_ints_as_strings'), ('courses', '0012_auto_20190330_0937'), ('courses', '0013_auto_20190330_1019'), ('courses', '0014_auto_20190331_0744'), ('courses', '0015_auto_20190404_1758'), ('courses', '0016_auto_20190404_1813'), ('courses', '0017_auto_20190404_1824'), ('courses', '0018_remove_course_rating'), ('courses', '0019_remove_course_views'), ('courses', '0020_auto_20190405_0926'), ('courses', '0021_course_date')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('img', models.FileField(upload_to='')),
                ('questionnaires_completed', models.IntegerField()),
                ('times_completed', models.IntegerField()),
                ('rating', models.SmallIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='test', max_length=8)),
                ('question_str', models.CharField(max_length=256)),
                ('answer', models.CharField(max_length=64)),
                ('fake_answers', models.CharField(blank=True, default='', max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New questionnaire', max_length=64)),
                ('questions_per_test', models.SmallIntegerField(blank=True, default=0)),
                ('ordered', models.BooleanField(blank=True, default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='courses.Course')),
                ('choices_per_question', models.SmallIntegerField(blank=True, default=3)),
                ('type_choice', models.SmallIntegerField(blank=True, default=85)),
                ('type_write', models.SmallIntegerField(blank=True, default=15)),
                ('auto_randomize_ints', models.BooleanField(blank=True, default=True)),
                ('include_answers_from_previous', models.BooleanField(blank=True, default=True)),
                ('number', models.SmallIntegerField(blank=True, default=0)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.Questionnaire'),
        ),
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.RemoveField(
            model_name='course',
            name='questionnaires_completed',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='rating',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='course',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='course',
            name='times_completed',
        ),
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='fake_answers',
            new_name='choices',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_str',
            new_name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='number',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['number']},
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='New course', max_length=64),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, default='Answer', max_length=64),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(blank=True, default='New question', max_length=256),
        ),
        migrations.AddField(
            model_name='course',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
