# Generated by Django 2.1.7 on 2019-05-27 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New course', max_length=64)),
                ('img', models.FileField(blank=True, upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(blank=True, default=0)),
                ('question', models.CharField(blank=True, default='New question', max_length=256)),
                ('answer', models.CharField(blank=True, default='Answer', max_length=64)),
                ('choices', models.CharField(blank=True, default='', max_length=1024)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New questionnaire', max_length=64)),
                ('number', models.SmallIntegerField(blank=True, default=0)),
                ('questions_per_test', models.SmallIntegerField(blank=True, default=0)),
                ('ordered', models.BooleanField(blank=True, default=False)),
                ('auto_randomize_ints', models.BooleanField(blank=True, default=True)),
                ('include_answers_from_previous', models.BooleanField(blank=True, default=True)),
                ('choices_per_question', models.SmallIntegerField(blank=True, default=3)),
                ('type_choice', models.SmallIntegerField(blank=True, default=85)),
                ('type_write', models.SmallIntegerField(blank=True, default=15)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='courses.Course')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.Questionnaire'),
        ),
    ]
