# Generated by Django 2.1.7 on 2019-03-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='other_posible_answers',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='questionnaires_completed',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='times_completed',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(blank=True, default='test', max_length=8),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='img',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='questions_ordered',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='questions_to_ask',
            field=models.SmallIntegerField(blank=True, default=10),
        ),
    ]
