# Generated by Django 2.1.7 on 2019-03-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190327_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='choices_per_question',
            field=models.SmallIntegerField(blank=True, default=3),
        ),
    ]
