# Generated by Django 2.1.7 on 2019-03-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_questionnaire_choices_per_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='multiple_choice',
            field=models.SmallIntegerField(blank=True, default=3),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='type_in',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
