# Generated by Django 2.1.7 on 2019-03-28 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190328_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='img',
        ),
    ]
