# Generated by Django 2.1.7 on 2019-03-28 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_questionnaire_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='fake_answers',
            new_name='choices',
        ),
    ]
