# Generated by Django 2.1.7 on 2019-03-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_question_other_posible_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='multiple_choice',
            field=models.SmallIntegerField(blank=True, default=80),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='type_in',
            field=models.SmallIntegerField(blank=True, default=20),
        ),
    ]
