# Generated by Django 2.1.7 on 2019-03-28 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20190328_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='multiple_choice',
            new_name='chance_choice',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='type_in',
            new_name='chance_type',
        ),
    ]
