# Generated by Django 2.1.7 on 2019-03-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20190328_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_str',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='questions_ordered',
            new_name='ordered',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='questions_to_ask',
            new_name='questions_per_test',
        ),
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='chance_choice',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='chance_type',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='type_choice',
            field=models.SmallIntegerField(blank=True, default=85),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='type_write',
            field=models.SmallIntegerField(blank=True, default=15),
        ),
    ]
