# Generated by Django 2.1.7 on 2019-03-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20190328_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='treat_ints_as_strings',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
