# Generated by Django 2.1.7 on 2019-03-30 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_questionnaire_treat_ints_as_strings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='treat_ints_as_strings',
            new_name='auto_randomize_ints',
        ),
    ]
