# Generated by Django 2.1.7 on 2019-03-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20190330_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='include_answers_from_previous',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='number',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='auto_randomize_ints',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
