# Generated by Django 2.1.7 on 2019-04-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20190331_0744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'ordering': ['number']},
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='New course', max_length=64),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, default='Answer', max_length=64),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(blank=True, default='New question', max_length=256),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='name',
            field=models.CharField(default='New questionnaire', max_length=64),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='questions_per_test',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
