# Generated by Django 2.1.7 on 2019-04-04 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20190404_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='rating',
            new_name='likes',
        ),
    ]
