# Generated by Django 2.1.7 on 2019-04-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20190404_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='likes',
            new_name='rating',
        ),
        migrations.AddField(
            model_name='course',
            name='views',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
