# Generated by Django 2.1.7 on 2019-04-04 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20190404_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='rating',
        ),
    ]
